### ISSUE TITLE
Support for OpenAPI

### ISSUE THREAD

**Issue by judepereira** [storyscript/hub#98]
- [x] validate the initial conversion
- [x] specify conversion properties
- [x] create service, and insert into openapi_metadata
- [x] display conversion errors

**Comment by JeanBarriere** [comment]
As a V1, we're telling the user we'll use the first server URL in the UI, and we can have this form extended whenever users ask for it

**Comment by judepereira** [comment]
We should have the form extended now itself, since the first entry for the pet store example itself is http, and the second is https. 


Cheers,
Jude Pereira

**Comment by williammartin** [comment]
We're not MVPing this feature for the pet store though? Does the person asking for support have multiple servers?

**Comment by judepereira** [comment]
I’m not sure. I thought that it’d be a good idea to test the entire flow end to end with the pet store sample - probably we could also self host the pet store and run integration tests on the converter. 

Is the work involved in adding the properties to the UI too much? 


Cheers,
Jude Pereira

**Comment by JeanBarriere** [comment]
Not too much work on the UI by itself, but we need to go back on the API to include the properties otherwise. And also think about other properties you might add in the future. I don't think we should do that now, as it'll work and if you own the spec, I guess you can easily change that order.
If it's really needed, I'll go back on the api to do the changes, otherwise I'm moving forward and complete the front for this feature
